### ISSUE TITLE
Field Team Coordinators Page

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#10]
When you first click on the Field Team Coordinators button from the home page, you see a table of existing Field Team Coordinators with access to the tool.

Searchable/sortable list including:
- [x] First Name
- [x] Last name
- [x] Phone number
- [x] Email
- [x] Authoritative Group

At top-right page , include a button to "Request to be a Field Team Coordinator," see issue

**Comment by jlholder** [comment]
This is different from the list of acct requests, more like a directory of coordinators. Not the list of requests

**Comment by jlherring** [comment]
@tommckennon are we excluding phone number from the directory for any specific reason? 
![image](https://user-images.githubusercontent.com/17882165/72819637-97753780-3c3b-11ea-907a-e4b8a4ef8223.png)
