### ISSUE TITLE
Add auth group input to the response/project request form. 

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#101]
Since auth group is handled at the response/project level we should request this info in this form. 

Since we will make changes here should we also move away from this email system and allow this form to create the response/project but with a pending status until a "coordinator admin" goes in and approves the response/project?

**Comment by jlherring** [comment]
No objection here. Would we just get a notice to go approve a new response?

**Comment by tbock** [comment]
Yep that's my thought.   Are we still the only ones creating response/projects?  If so yes just provide link to response/project in admin with a approve or enable or something check box.   If its becoming a bigger group then we could discuss adding to the main UI with a cleaner process.

**Comment by jlherring** [comment]
Yeah, we’re still the only ones creating new responses/projects. I don’t see that changing soon

**Comment by tbock** [comment]
Doing this for now and will address issue #102 after this PR is merged/deployed.
