### ISSUE TITLE
Allow admin to set default reason/affiliation for a project

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#103]
Right now, all default to ER, which is no longer the majority.

Thinking we add it to the request form in #99 to allow the coordinator to submit. Then we can automate it into the set up.

**Comment by abprins** [comment]
In the admin interface, we can set the default reason/affiliation for each project. If that's what this is referring to, then yes it's resolved @tbock.

![image](https://user-images.githubusercontent.com/62261480/191771046-00a9f8a5-428e-43d1-86aa-175d037ed1cf.png)
