### ISSUE TITLE
Some approved accounts aren't being created

### ISSUE THREAD

**Issue by abprins** [USEPA/GeoPlatform-Request-Tool#110]
Some account requests that we are not responsible for are being approved but not created. I've tried to force the account creation using the normal method in the app, but it doesn't do it.

![image](https://user-images.githubusercontent.com/62261480/169324597-37ac5d81-c92b-46f7-a694-7450ae560987.png)

**Comment by jlherring** [comment]
@abprins I'm seeing apostrophes in all the names... edit those out of the usernames and try again?

@tbock may need to build in so we strip those out. I thought we were, but maybe not

**Comment by abprins** [comment]
@jlherring, @tbock that worked.

**Comment by tbock** [comment]
I suspect PR #114 also applies to this issue.  Invalid usernames should produce a red error with a message of ```Username is invalid or unavailable.  Please edit.``` now.
