### ISSUE TITLE
No option to go to table view if already logged in

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#111]
If you're already logged in to the tool on the home page, there's no longer an option to navigate to the approval table. You have to log out and log back in

![image](https://user-images.githubusercontent.com/17882165/169549952-543967e2-3b0a-4cd9-9c63-956a3435ae1d.png)

**Comment by tbock** [comment]
The UI checks for a specific permission for that user that is required view account requests.  If they don't have that permission they wont be able to see the requests anyways.  I'm closing this is a user config issue. Reopen if you can replicate this on a user with the correct permissions.
