### ISSUE TITLE
New welcome email text for MFA

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#112]
@tbock  Once an account is created, people will have a 2-week grace period to enable MFA. @torrin47 has updated language for those automated emails when accounts are created. We'll need to update

**Comment by tbock** [comment]
@torrin47 @jlherring what is the updated language?

**Comment by torrin47** [comment]
[welcomeExternal.txt](https://github.com/USEPA/GeoPlatform-Request-Tool/files/9781331/welcomeExternal.txt)

Template html attached!
