### ISSUE TITLE
Provide username suggestions when a username exists but is associated with a different email address

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#113]
Last.First2_EPAEXT is an example of a suggestion.

**Comment by jlherring** [comment]
getting more questions about this... making high priority for good measure

**Comment by tbock** [comment]
Eh this is very similar to #137 .  We don't provide suggestions b/c a matching username isn't an error here.   When would we even offer suggestions?  What scenario? @abprins @jlherring

**Comment by tbock** [comment]
re titled issue and will work from there
