### ISSUE TITLE
Configure New Response page

### ISSUE THREAD

**Issue by jlholder** [USEPA/GeoPlatform-Request-Tool#12]
When a user clicks the "Configure New Response" button, it takes you to a new page with a form (similar to existing acct request form).  A user provides the following info:
- [x] Name of the new response (required)
- [x] List of Field team coordinators associated w/ the response (required)
- [x] GeoPlatform groups used for the response (required)
- [x] Name of the person requesting the new response
- [x] Phone of person requesting the new response

The list of field team coordinators could be handled in a few ways. If a person isn't already in the tool, we'll need all their info from issue #11. If they are already in the tool, we'd only need their name to add the existing acct to the response. Thinking we keep it simple for now and just have free text feel to add list of coordinators.

Then, include the last 2 fields (name/phone of person requesting the new response) so we have someone to contact w/ any follow-up questions. 

Submitting the form sends an email w/ all of the included info to an admin email (actual acct tbd).

**Comment by torrin47** [comment]
Just to be clear, the "Name of the person requesting the new response" will be considered the "sponsor" for any new accounts created during the response, right? Sounds perfect to me.

**Comment by jlholder** [comment]
@torrin47 yes. and then related to #8, we just have to figure out how to also add delegates. i.e. Cheryl is the sponsor and requested the new response, but Rob and I would also have permission to hop in an approve based on her direction
