### ISSUE TITLE
Change language on any relevant form inputs/text to drop GeoPlatform

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#130]
At minimum this needs to be updated for the response/project request form but there are likely other places.

Is just dropping GeoPlatform too vague?  

Nearly everyone has no idea what Role even is so dropping that is fine I think and they will just go with default. Should probably  add help text that says leave this default unless you know what you want and we can discuss further after we receive the request? 

For groups, what about User Groups? 

On the edit properties dialog, in the approval list, just drop it from username (also switch to User Groups). 

@jlherring does that work?

**Comment by jlherring** [comment]
![image](https://user-images.githubusercontent.com/17882165/225114040-71eadb2e-ab64-4418-9489-14901ef41d56.png)

**Comment by rdmccann** [comment]
![image](https://user-images.githubusercontent.com/850762/226683082-751936b6-e3ee-4377-9bd7-6911f93668b3.png)

There's a few other notifications as well that reference GeoPlatform, but the language is similar.

**Comment by jlherring** [comment]
Ahh good point - @rdmccann are we able to distinguish in the email and put GeoPlatform vs GeoSecure in these? Anything GeoPlatform we can automatically approve, but anything GeoSecure, we'll have to run up the chain and make sure the sponsor did their paperwork first

**Comment by jlherring** [comment]
Works for me! We will prob also need to update the "Important Points" section, but I'm not sure we have that language yet. I'd say do what you need to do to make sure the GPO email and the GeoSecure email can be diff messages?
