### ISSUE TITLE
Remove/Update GeoPlatform language on landing page

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#131]
Related to #130 , more detail:

Update the intro text to: The Account Request Tool provisions EPA GeoPlatform (GPO) and EPA GeoSecure user accounts during emergency response events and projects. Authorized users (Team Coordinators) can rapidly set up accounts for field data collection events and provide access to specific groups in either environment. Visit the [Help Documentation](https://raisz.epa.gov/request/assets/AcctRequestUserGuide.pdf) for additional information.

![image](https://user-images.githubusercontent.com/17882165/225111546-3f500d71-4ccb-43a2-80dc-7033189454c0.png)

**Comment by tbock** [comment]
@rdmccann Here is another one for reference.  Please confirm if we got all of these already

**Comment by jlherring** [comment]
I like it @rdmccann
