### ISSUE TITLE
Include info about adding delegates to the Response Approval email

### ISSUE THREAD

**Issue by abprins** [USEPA/GeoPlatform-Request-Tool#133]
If requestors don't initially set a sponsor or request delegates, I usually follow up personally to explain the purpose of delegates. Maybe we could include a blurb about that in the approval email?

![image](https://user-images.githubusercontent.com/62261480/226370262-fa3aa2de-7c7f-4dbe-820a-17a35c194767.png)

**Comment by tbock** [comment]
@abprins Sounds good.  Can you drop some text in here that we can use?

**Comment by abprins** [comment]
@tbock
Probably goes after "Requests can be reviewed and approved here: https://r9data.response.epa.gov/request/accounts/list"
	

> One or more "Delegates" can be designated to review and approve account requests on behalf of the Sponsor. Sponsors must be EPA staff; Delegates can be contractors. If you'd like to set any Delegates, please reply to this email with a list of users and their email addresses.

**Comment by rdmccann** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/850762/226655495-4d4ea5ed-5250-44f6-a987-f135e636a867.png)

**Comment by abprins** [comment]
@rdmccann looks good to me.
