### ISSUE TITLE
Update approval message for existing accts

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#136]
So ran into this in GPO account request and suspect it will be a bigger issue in GeoSecure. A request was submitted for an existing EPA account. I changed the username to the current LAN, but when I hit approve, I still get the "Email" or "Password" options... so what actually happens here?

Will they get a generic email even if their acct already exists? I can't reset their LAN password, so not clear what that does.

Think we it's an existing account, the button should be "Add to Group" or something similar. Which also begs the question - do we notify them that they have access (particularly thinking GeoSecure, but no reason it couldn't apply to both). I know you'll see a notice in the banner of AGOL/Portal that you've been added, but someone wouldn't know to log in and check if we don't notify. They could just be waiting.

Thoughts?

![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/17882165/ce346ba6-0a62-47d4-afa2-adaa640dfda0)

**Comment by tbock** [comment]
Updates pushed to new staging environment.  Please review there.
