### ISSUE TITLE
Move incremental numbering for external accounts

### ISSUE THREAD

**Issue by abprins** [USEPA/GeoPlatform-Request-Tool#137]
Currently, external accounts created through the tool have their incremental numbering at the end of the account name (**name.name_EPAEXT2**). According to Barb, the numbering should be after the name (**name.name2_EPAEXT**). It looks like accounts created through the Dashboard do it the way Barb describes.

**Comment by tbock** [comment]
Something kept bugging me about this and I think I finally figured out what it was.  Our tool doesn't do now this and can't.  We allow existing users to be entered.   Do we really have a way of knowing if the request is truly a new account or for existing account?  @abprins @jlherring
