### ISSUE TITLE
Error message for GeoSecure/EPA emails

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#138]
So I'm guessing this HAVE to be an EPA email for GeoSecure accounts?
![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/17882165/2283f127-3ef6-4d6c-a394-728a1660f04d)

When I plugged in my Innovate email. I kept getting the "Request can not be accepted at this time." - which didn't help me figure out what was going on 
![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/17882165/50499eae-72e1-47e8-8a47-0a85c0c9d04f)

Let's either add something explicit in the help about GeoSecure and using your EPA email and/or update the snackbar to say "GeoSecure Users must provide an EPA Email address."

**Comment by tbock** [comment]
This was a configuration issue.  Once the epa.gov domain was added to the approved list I believe you were able to submit the request.  Can you confirm @jlherring?  Please reopen if I'm incorrect.
