### ISSUE TITLE
Did not add existing acct to GeoSecure group

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#139]
GeoSecure approval did not automatically add me to the Drinking Water demo group; errored out
![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/17882165/d6133184-d25a-4470-871c-866047b53188)

**Comment by tbock** [comment]
Fix deployed to staging and I was able to approved the above request and account is now showing in the group.  Closing but reopen if needed.
