### ISSUE TITLE
Did not create new GeoSecure acct

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#140]
See Rob's entry - approved but did not create new acct in GeoSecure staging

**Comment by tbock** [comment]
Bug related to dealing with role types across multiple systems (since esri reuses role ids).  Bug resolved and account created successfully.   Should probably have rob login to geosecure staging now to complete test. @jlherring

**Comment by tbock** [comment]
I had him login and the account worked correctly and he was in the expected group.
