### ISSUE TITLE
Admin Portal Selection confusing

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#141]
When I log into the admin now, I am only ever creating responses for the acct I used to log in (GPO vs GeoSecure). So when adding a completely new response, choosing the Portal not only doesn't make sense, but it isn't accurate. So logged in w/ my GPO acct, I can select GeoSecure - but when I create/save the response, it is still associated w/ the GPO. 

Possible solution is autopopulate the Portal??

![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/17882165/c6b0fd1a-80cc-43f4-a6e0-54ed8e3c08ea)

**Comment by tbock** [comment]
Pushed changes to hide this field when creating a response but show it as a read only for support reasons after response is created.  Superusers can also edit for support reasons (if someone creates response under wrong portal and needs to move it mainly). Please review and reopen issue if needed.
