### ISSUE TITLE
GPO Requests not going through

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#142]
I've gotten success snack and this weird outstanding snack, but nothing is going through - no requests show up in the admin or accounts list

![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/17882165/f2b30ca7-db7a-4d0f-8151-efdb1ccafcf9)

**Comment by tbock** [comment]
What email address did you use when submitting this?

**Comment by tbock** [comment]
@jlherring ☝️

**Comment by jlherring** [comment]
innovate email @tbock. went and deleted old outstanding requests and seems to be fine. seems to be recognizing a request for the specific response (i.e. I can put mult requests in for diff responses, but not same response). so maybe we're good here?

**Comment by tbock** [comment]
Sounds correct to me.
