### ISSUE TITLE
Can't change sponsor - 400 error

### ISSUE THREAD

**Issue by abprins** [USEPA/GeoPlatform-Request-Tool#144]
Trying to change the sponsor on a response throws this:
![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/62261480/530c0498-ec31-4b03-91fb-fae78c4f5008)

**Comment by tbock** [comment]
@abprins was this for new version or was this in production now?

**Comment by tbock** [comment]
Wait was this really the issue with the very long list of requests? I believe it was.  This is resolved.

**Comment by abprins** [comment]
Yeah this was for the production version, for the response with a ton a requests.
