### ISSUE TITLE
Updating a username in the admin appears not to perform the username check and thus not update the username is valid status

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#145]
Updates to the admin (not just frontend) should refresh the username valid check.

**Comment by tbock** [comment]
@abprins anything else to add?

**Comment by abprins** [comment]
I'm not sure if you can go back through my recent actions in the admin to verify this, but I'm nearly positive that I've changed that attribute a few times from the admin backend, and from what I remember it did update the front-end validity status.
