### ISSUE TITLE
Update role/response names 

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#15]
Per Torrin:   Language change is minimal – does it need to be Field Team Coordinator, or could it be Team Coordinator, or Project Coordinator, or EPA Coordinator?  Response could be changed to “Collaboration” or “Initiative” or “Project” or “Effort”.

**Comment by jlholder** [comment]
Per Cheryl: 
Use Team Coordinator
Use Project, but add in help documentation that a project = response

**Comment by jlherring** [comment]
done!
