### ISSUE TITLE
Strip non-alphanumeric characters from names when creating username.

### ISSUE THREAD

**Issue by abprins** [USEPA/GeoPlatform-Request-Tool#151]
GPO usernames with punctuation (apostrophes etc.) that are suggested through the Account Request Tool can't be created through the tool until the punctuation is manually removed. I think we need a little warning message when this happens.

![image](https://github.com/USEPA/GeoPlatform-Request-Tool/assets/62261480/f1d3f5b5-3899-4e9e-83ae-8bbc6d640bf4)

**Comment by tbock** [comment]
I think we just strip non-alphanumeric characters automatically.  That ok @abprins  This does not count the dot in the username.

**Comment by abprins** [comment]
@tbock yeah that's even better.
