### ISSUE TITLE
Add "reason" for account creation

### ISSUE THREAD

**Issue by jlholder** [USEPA/GeoPlatform-Request-Tool#16]
Per Torrin: Can’t assume “reason” for account creation (one of sponsorship metadata elements) is Emergency Response. Could we add:

- [ ] domain-restricted “Reason” and
- [ ]  free-text Description to this tool

Those are mandatory fields in dashboard.

**Comment by torrin47** [comment]
The domain for "Reason" includes the following values. Not sure where this list came from, as some of the values are clearly non-exclusive, but it seems to work. I would think that it would be practical to set a default "Reason" for a given response.  If it's easy to then allow reason to be configurable on a user-by-user basis after that, then that might be nice, but that priority would be extremely low. Setting one blanket value for a response would be fine.  The same goes for description, which is free text.

Emergency Response
Other Federal Agency
State Agency
University
Long Term GIS Support
Non Government Organization
Tribal Government
Citizen Advisor
Other

**Comment by jlholder** [comment]
Great! We shall use this strange list.

@tommckennon - the reason will be added to the Request GPO account section, so actual acct requests (not configuring coordinators).
