### ISSUE TITLE
Update emails for production

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#17]
Need to create/access a formal email to send all requests before pushing new UI to master

**Comment by jlholder** [comment]
Cheryl requested the acct 12/10/19

**Comment by jlholder** [comment]
Acct provided: GPOAccountRequest@epa.gov

But not about to sent to EPA listservs from non-EPA Accounts

**Comment by jlherring** [comment]
To get emails working in production, go ahead and hardcode Cheryl (Henley.Cheryl@epa.gov), Jenny (jholder@innovateteam.com), and Rob's (rhomsher@innovateteam.com) emails in the tool (not a group email/listserv). This will allow us to demo the tool fully before we find out exactly who's emails should be added from elsewhere in EPA

**Comment by tbock** [comment]
@tommckennon Can you make a change so EMAIL_RECIPIENT setting config is an array of emails and adjust code as necessary.  Also the FROM address for all emails should changed to an separate config which can be set to GPOAccountRequest@epa.gov

**Comment by jlherring** [comment]
@tbock did this get done when we chatted about it the other day?

**Comment by tommckennon** [comment]
Hey @tbock . For this update, the local_settings module just needs to be updated with the following:
GPO_REQUEST_EMAIL_ACCOUNT = 'GPOAccountRequest@epa.gov'
RECIPIENT_EMAILS = ['Henley.Cheryl@epa.gov', 'jherring@innovateteam.com', 'rhomsher@innovateteam.com']

I suspect the RECIPIENT_EMAILS might need to be adjusted/finalized, but I believe these are the email request recipients to start.

**Comment by tbock** [comment]
deployed.
