### ISSUE TITLE
Coordinators Request - update Region to Auth Group

### ISSUE THREAD

**Issue by jlholder** [USEPA/GeoPlatform-Request-Tool#18]
Let's change the test from "Region" to "Authoritative Group" to match the GeoPlatform Dashboard. Then, in addition to the regions, let's add the following options to the drop-down:

- EPA Office of Administration and Resources Management (OARM)
- EPA Office of Air and Radiation (OAR)
- EPA Office of Chemical Safety and Pollution Prevention (OCSPP)
- EPA Office of Enforcement and Compliance Assurance (OECA)
- EPA Office of Environmental Information (OEI)
- EPA Office of General Counsel (OGC)
- EPA Office of Inspector General (OIG)
- EPA Office of International and Tribal Affairs (OITA)
- EPA Office of Land and Emergency Management (OLEM)
- EPA Office of Research and Development (ORD)
- EPA Office of Water (OW)
- EPA Office of the Administrator (OA)
- EPA Office of the Chief Financial Officer (OCFO)
- OLEM - ER Program Support

**Comment by tommckennon** [comment]
Added this issue to issue #11 .
