### ISSUE TITLE
Add user to groups using existing acct

### ISSUE THREAD

**Issue by jlholder** [USEPA/GeoPlatform-Request-Tool#2]
Right now, when a sponsor logs in, they can only approve a new account and assign that new account to groups.

To assign an existing user to groups, the sponsor currently has to go back to the GeoPlatform.

Can we add an option in the sponsor page to select an existing acct and use it?

**Comment by tbock** [comment]
Maybe we should just reject account requests that have a matching username and email and tell them to go to geoplatform to get group access.

**Comment by tbock** [comment]
Or is that too much friction ... just create the accounts b/c its related to emergency response and clean up the duplicates later.

**Comment by jlholder** [comment]
Set up to show user if someone already has an acct and gives option to replace username w/ an existing one to just add them to groups (not create another acct)
