### ISSUE TITLE
Username issues in request list

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#27]
I'm getting the error that my username already exists no matter what I enter (even though this name 100% certain does not exist already)...

And on top of that, even if it does exist, it should still allow me to approve and just modify existing groups like the hover-over says:
![image](https://user-images.githubusercontent.com/17882165/77077019-0a482800-69cb-11ea-947b-830ed46de102.png)

**Comment by tbock** [comment]
Needed to login again with admin creds
