### ISSUE TITLE
Redirect URL needs to be updated in pending requests

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#28]
Need to update the email to Sponsor when a new request is submitted in the tool b/c the link is still pointing to the old URL:
![image](https://user-images.githubusercontent.com/17882165/77431245-cc744680-6db2-11ea-8d4b-128712f4d563.png)

Let's update the body of the email to look more like other email notifications:

GeoPlatform Account Request(s) is pending your approval in the GeoPlatform Account Request Tool (request.ercloud.org).

Please log in to the [GeoPlatform Account Request Tool Approval List](https://request.ercloud.org/accounts/list) to configure new GeoPlatform accounts and notify the users when configuration is complete.

**Comment by jlherring** [comment]
@tbock updated the email text in master whenever you wanna deploy it

**Comment by tbock** [comment]
done
