### ISSUE TITLE
Pending requests email to Sponsor AND delegates?

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#29]
So only Cheryl received the pending requests email. Can we confirm - pending request notifications need to go to the sponsor indicated AND that's sponsor's delegates.

**Comment by tbock** [comment]
Emails should now be going to sponsor and delegates.  However, since we moved the email notification sending to onsite at R9 it is completely down.  Perhaps we can move this script to another location.... hint hint.

**Comment by tbock** [comment]
Done.  and servers are back up
