### ISSUE TITLE
When editing username manually and saving an error is throw

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#3]
Expected behavior is that the request record saves and if the username exists a tooltip explain that the users groups will be changed but no new account created.

**Comment by jlholder** [comment]
@tbock I think we're good here?

**Comment by tbock** [comment]
IDK... is it working as expected?

**Comment by jlholder** [comment]
nope. works if you don't edit the username. still throwing an error if you change the username.

**Comment by jlherring** [comment]
still this @tbock

**Comment by tbock** [comment]
closed b/c partially fixed and remaining is in more specific issue #34
