### ISSUE TITLE
Sponsor ID numbers don't correspond to sponsors

### ISSUE THREAD

**Issue by torrin47** [USEPA/GeoPlatform-Request-Tool#37]
The list of accounts here:
https://request.ercloud.org/api/v1/account/approvals/
includes the following referenced sponsor IDs: 3,6,7,8
But the sponsors endpoint here:
https://request.ercloud.org/api/v1/account/approvals/sponsors/
has only two sponsor IDs, only one of which matches: 7, 12.  
It looks like the other sponsor IDs correspond to delegates rather than coordinators. Perhaps there's a reason to preserve the delegate ID for an audit trail, but from the perspective of general GeoPlatform administration, the coordinator is the official sponsor. We should be ok if we can link accounts to projects/responses, but we're not seeing anything in the schema or API that connects accounts to projects/responses. Are we missing something obvious?

**Comment by tbock** [comment]
Those records almost certainly were created before we really restricted the sponsors to true sponsors and added the delegate stuff.  We probably need to go back and clean it up.  For example Jenny is 3 and should be 7 which is Cheryl.  Should be quick clean up.

**Comment by jlherring** [comment]
Soooooooo Cheryl switches b/t 2 GeoPlatform accounts. So she is both 7 and 8. Is that an issue @torrin47?

But Travis was right - did have to take me/Rob off of some records created prior to the delegate option. Those are all cleaned up now.

**Comment by torrin47** [comment]
All that really matters is having a reliable way to link requested accounts to a sponsor geoplatform account. Doesn't matter to us if a sponsor bounces between accounts unless they somehow want us to reconsolidate their sponsees under one account later. If we can use the integer ID and the sponsors endpoint to make the link, we're good.  

Still curious, though, about the question I meandered to. Is there any explicit way to tell which requests are associated with which project/response? Or is that just implicit based on which groups they're assigned to?

**Comment by jlherring** [comment]
hmm we could get there in a around-about way... but it isn't explicit if the sponsor/delegate is associated with multiple projects/responses. (GeoPlatform groups are associated with a project/response, and we're updating it so you also don't HAVE to add a user to a group). 

So it could be auto-assigned IF a sponsor/delegate is only associated with one response. Or, if they're associated with multiple, it could be a drop-down in the request approval process? The drop-down is populated with the names of the responses the sponsor is part of and they select one?

**Comment by torrin47** [comment]
Hrm, so in the tool, a project/response is really only a mechanism to link coordinators to delegates?
But if, as you say, a coordinator is associated with multiple projects/responses, and has different delegates for each project/response, how do requests end up in the right queue for the right delegates? The new user request form doesn't ask users what project/response they're involved in, it asks them who their coordinator is. If there's not some connection between users/responses/delegates/coordinators, what's the point of separate project/responses? 

If we want to use group membership as an implicit way to connect users to responses I think I'm ok with the assumption that every project/response will always have at least one dedicated group, but we'd need to make that assumption clear up front before the coordinator creates the project/response.

**Comment by tbock** [comment]
Request form now asks for response/project instead of Sponsor.  Multiple sponsors can be assigned to a response/project for notification purposes.  However, the final actual sponsor is selected when the account is approved.  Either automatically b/c approver IS a sponsor or based on who the delegate is a sponsor for (if only 1 possible the sponsor is automatically selected as well in the form).  In either case the sponsor is required before a account can be approved. 

Not using group membership implicitly.  Response/project assignment is explicit and sponsor becomes explicit at account approval. 

Please review @torrin47

**Comment by torrin47** [comment]
I'm not seeing the term "sponsor" in the request tool, just the term "coordinator". Are those functionally synonyms?

**Comment by jlherring** [comment]
Correct. I can't remember who decided on that change, but that was tweaked fairly early on. Admittedly, I think we still say "sponsor" everywhere on the Django admin side, but those are one and the same.

**Comment by tbock** [comment]
Can this be closed?

**Comment by jlherring** [comment]
If @torrin47 says it can be closed, I'm good

**Comment by torrin47** [comment]
Done.
