### ISSUE TITLE
Suggest Description field be initially populated with the project/response name

### ISSUE THREAD

**Issue by torrin47** [USEPA/GeoPlatform-Request-Tool#39]
This isn't a requirement, just a time-saving thought, since the intent of the description field is a succinct overview of why the account was created, and the project/response title is a great starting point for that.

**Comment by jlherring** [comment]
#41 would allow us to make this happen more easily

**Comment by tbock** [comment]
@torrin47 we are making description optional and NOT auto-populating with anything now that responses are a distinct field.  We are leaving in case someone wants to wax poetic about the account but otherwise it will be empty.

**Comment by tbock** [comment]
issue #45

**Comment by torrin47** [comment]
Hrm. So there will minimally be an implicit connection between a user and a response based on the groups the user belongs to. If a user is associated with multiple responses, are you populating the response field with a list of those response ids?  I'm still kinda interested in the response names being visible in the GPO Dashboard, so if it's all the same to you I'd be inclined to ignore someone's poetic waxings and just pull the list of responses (or honestly the most recent response would be sufficient) when we harvest from you.

**Comment by tbock** [comment]
There is now an explicit connection between an account being created and the response/project they are requesting. So you can just get it through that relationship.  See below.
`{
            "id": 73,
            **"response": 1,**
            "first_name": "Apollo3",
            "last_name": "Apollo3",
            "email": "aherring@innovateteam.com",
            "possible_existing_account": "",
            "organization": "innovate",
            "username": "Herring.Apollo3_EPAEXT",
            "username_valid": true,
            "sponsor_notified": false,
            "reason": "Emergency Response",
            "description": "",
            "submitted": "2020-06-17T14:18:48.925793Z",
            "approved": "2020-06-17T15:34:57.477891Z",
            "created": "2020-06-17T15:34:58.087230Z",
            "agol_id": "4961c10b-1e2b-43e4-a2e3-bcf1a2934063",
            "role": "jmc1ObdWfBTH6NAN",
            "auth_group": "f1e93918-5899-418b-95a1-430356962959",
            "sponsor": 7,
            "groups": []
        }`
and the response available at /api/v1/responses/
`{
            "id": 1,
            "name": "R9 Site Assessment"
        }`

**Comment by torrin47** [comment]
Yup, saw that, and that's why I was inclined to harvest that info and stuff it into our Description field and ignore your Description field.  My only question was whether account/response was always 1:1, or whether an account could be assigned to more than one response, but I guess I realize this object isn't a user object, it's a request object. So a request can only be associated with one response, but the sponsor could associate the request with an existing GPO account, and that account might end up with multiple request objects in your database.  So if we care about all the responses a user is associated with, we just get that from your API and handle it on our end. Sweet. Case closed.
