### ISSUE TITLE
Track requests by response

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#41]
So, are we thinking we switch Team Coordinator to Response in the request form?

![image](https://user-images.githubusercontent.com/17882165/82566020-53426700-9b49-11ea-96c4-15c7e037930d.png)

Emails can still go out to sponsors (and their delegates) associated with the response.

B/c there could be multiple sponsors associated with a response (folks coming in to help from other regions), in the Approval List, the Team Coordinator would be blank by default:

![image](https://user-images.githubusercontent.com/17882165/82566260-a4525b00-9b49-11ea-8221-c1a4cc62a33f.png)

Similarly, then we would automatically have the response someone is associated with and allows us to auto-populate the Description w/ the Response name (but still editable) re #39 .

This allows us to cast a wider net when assigning people who can approve the accounts, but provides more concrete description info and forces the user to intentionally pick a sponsor.

**Comment by torrin47** [comment]
👍  Definitely what I had in mind - seems intuitive.

**Comment by tbock** [comment]
Yeah my only concern was keeping up with the "responses".  Sponsors don't change often but responses might?  But I guess, this response configuration was already kinda of required b/c of how the groups list is populated?  So do we think we can just leverage that and that will be enough?

**Comment by tbock** [comment]
done and deployed
