### ISSUE TITLE
Move Roles and Authoritative Groups to a managed table b/c they will change over time

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#43]
Currently Roles are hard coded into the system but this looks like it need to be moved to a table so admins can manage this list moving forward.

**Comment by tbock** [comment]
@jlherring is the same for authoritative groups?  I know its hard code but looks to have same issue of likely changing over time (albeit slowly)

**Comment by tbock** [comment]
Roles is a new table and a check box has been added to group to identify auth groups.

**Comment by torrin47** [comment]
How does a coordinator communicate to the admin team which role their response should be assigned to? Role isn't a choice on the Response / Project Request Form, so does that just happen via email?

**Comment by tbock** [comment]
@jlherring Seems like @torrin47 question never got answered ☝️ ... Since we are discussing making changes to the response/project form this seems like a good time to add the role to the form as well? Unless there was a reason it wasn't included.  Only reason I can think is b/c of simplicity.  Most sponsors/coordinators don't know the answer to this and just want the default.  Do we provide the default with explanation or do we just use default unless they know to ask otherwise.

**Comment by jlherring** [comment]
Yeah, always just been a convo in the past. Now that we have so many groups, prob worth tossing it in the form, especially since we’re simplifying from two forms to one anyway
