### ISSUE TITLE
What's happening in this description?

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#45]
When we talked yesterday, we were thinking the description would be a drop-down of response names. It would not be required, b/c if you didn't select anything, it defaulted to the name of the response the request is assigned to. 

I does not appear to be required in the form, but looks like we still have the logic set up so the Approve button won't appear if it is empty.

It is still showing up as a text field, no drop down. So what is this guy for?
![image](https://user-images.githubusercontent.com/17882165/84903936-b6f27e00-b07c-11ea-9afe-eb9bc8c28e38.png)

**Comment by tbock** [comment]
Its not a selection b/c response/project selection is already made.  It might be pointless now. 

I will double check but the account selected in the screen shot also shows that the sponsor wasn't set yet.

**Comment by tbock** [comment]
fixed
