### ISSUE TITLE
Define roles w/in an AGOL group?

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#48]
Chatted with Blair and there will be a few levels of access in the Survey123 groups.

1. EPA people that can see/edit everything (cool, doesn't really need to be handled w/ this tool)
2. State partners that can see everything but filter content to only their state
3. Citizen scientists that can only see what they submit. 

So we may need to determine if we can not only assign users to an AGOL group, but determine if they are a group member vs. group owner/manager. 

So, if members are allowed to edit content in a group, can they edit everything (state partners) or can they edit only their own stuff (citizen scientists).

**Comment by tbock** [comment]
Seems like something that should be handled in AGOL

**Comment by torrin47** [comment]
Agree with Travis - those granular access levels can be handled by assigning the users to appropriate groups, and using those groups to control the level of access for items. So managers should be in one AGOL group, and citizen scientists should be in a separate group. The invite tool can help with group assignment, but all the rest of the permission setting is up to the application owner. 

It may make sense in the context of Blair's application for each type of user to be handled as a separate "response" so the distinction between groups/access levels is more explicit.
