### ISSUE TITLE
AGOL group drop-down not populating

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#52]
So I have my AGOL groups assigned in the admin: 
![image](https://user-images.githubusercontent.com/17882165/85421903-f91b3400-b542-11ea-9bd1-b36e4a30d0d2.png)

But nothing shows up when I select my response on the front end:

![image](https://user-images.githubusercontent.com/17882165/85421929-03d5c900-b543-11ea-9c6b-99bd8229ed7e.png)

**Comment by tbock** [comment]
unable to reproduce.

**Comment by tbock** [comment]
reworked how people can access responses/groups.  Sponsors only are now assigned to a response and delegates inherit access to these response and the agol groups related to the response

**Comment by jlherring** [comment]
muuuuuuuuch better

**Comment by torrin47** [comment]
Still can't seem to get anything to appear in the responses dropdown - getting a 500 error under the hood:
![image](https://user-images.githubusercontent.com/2127036/85797536-d38c5700-b709-11ea-9057-8bb41ee98f54.png)

**Comment by tbock** [comment]
yeah got the error msg.  fix incoming.

**Comment by tbock** [comment]
This was actually a different issue but its fixed @torrin47
