### ISSUE TITLE
Update acct approval form

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#54]
"Response" --> "Response / Project"

"Reason" --> "Reason / Affiliation"

**Comment by tbock** [comment]
You will be assigned to this reason / affiliation.
... makes no sense now...

not exactly sure what to change it to

**Comment by jlherring** [comment]
Where you seeing "You will be assigned to this reason / affiliation." @tbock ?

**Comment by tbock** [comment]
ignore me
