### ISSUE TITLE
Sponsor/Delegate not inheriting permissions

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#56]
Started testing w/ Blair. He is not able to see any account requests unless he is a superuser.

Something is definitely off with the Sponsors/Delegates.

He still could not see requests as a Delegate to Sam, as a Sponsor himself, or as a staff status. Could only see them as a superuser.

He is presenting to the OW team today at 9am PST/12noon EST. If we can tweak before then, awesome. If not, need to wait until this afternoon.

**Comment by tbock** [comment]
who is he a delegate for?

**Comment by jlherring** [comment]
Samantha Fontentelle

**Comment by tbock** [comment]
Fixed and deployed.
