### ISSUE TITLE
Remove Sponsor from required checks before approval

### ISSUE THREAD

**Issue by tbock** [USEPA/GeoPlatform-Request-Tool#60]
Sponsor is now captured automatically based on who the approver is and can no longer be physically selected.  This requirement for approval needs to be removed in order to prevent any confusion.

**Comment by tbock** [comment]
I believe this is no longer true.  I see no current issues around this.  @abprins @jlherring ?

**Comment by tbock** [comment]
Anyone get a chance to confirm if this is still an issue? @abprins @jlherring

**Comment by abprins** [comment]
I haven't encountered any problems around this @tbock.
