### ISSUE TITLE
Paging not working in list view

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#62]
Paging does not appear to be working from the list view. I cannot change pages, and changes Items per page does not affect the number displayed. I can tell there are definitely more than 25 records total b/c I see different entries when I sort by name/org/etc.

![image](https://user-images.githubusercontent.com/17882165/88671271-1ac48980-d0b4-11ea-9f19-d2b442656977.png)

**Comment by tbock** [comment]
fixed
