### ISSUE TITLE
Prevent users from submitting multiple requests

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#66]
If possible, prevent the user from clicking submit again before the request has gone through - users continue to click submit until they see the page update, leading to a ton of duplicate entries for each request.

**Comment by tbock** [comment]
I don't think this is a click thing... before the request is even sent to the server the submit button is disabled.  Also some of the duplicates are actually slightly different so I suspect people are not realizing that the form submitted.  Adjusted snackbar messages to make more visible and require dismiss on success.  

additional actions
1) send confirmation email to requestor
2) prevent duplication submissions based on email if they have an unapproved request already.
