### ISSUE TITLE
Add AGOL group down-down to acct request

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#67]
Feedback from START - if possible, team would like to also select which groups a user needs access to in the account request itself. 

First time hearing this, so putting it in the parking lot to see if we can any additional/similar feedback.

Maybe populate the groups after the user selects a response? Make groups optional?

**Comment by tbock** [comment]
Seems like this is overcomplicating it.  One of the main goals with this process is trying to keep it as simple as possible.  The current request form is for anyone, including the public.  It maybe be necessary to create a new form inside the list to allow delegates and sponsors to enter account requests directly.

**Comment by jlherring** [comment]
Cheryl agreed to keep it simple, closing this one
