### ISSUE TITLE
Expose agol account of sponsors via REST API

### ISSUE THREAD

**Issue by torrin47** [USEPA/GeoPlatform-Request-Tool#70]
The GeoPlatform Dashboard requires agol accounts as unique identifiers of sponsors, but the request tool only exposes the full name and email address of sponsors - and many GPO admins have many agol accounts tied to their name and email address. 

Since the agol account of each sponsor is stored in the request tool database for login purposes, it would be very helpful if that account could be exposed via the REST API - minimally at the api/v1/sponsors/ endpoint. 

Even better would be including the sponsor agol account in the api/v1/account/approvals/ object!

**Comment by tbock** [comment]
Can't just add it to the sponsors endpoint b/c that is exposed publicly... could conditionally add it there but instead going to conditionally add it to the approvals endpoint.  To get details you must add `include_sponsor_details=true` query parameter.  This will change the sponsor attribute to a nested object with all sponsor details including username.

**Comment by tbock** [comment]
Deployed: https://request.ercloud.org/api/v1/account/approvals/?include_sponsor_details=true

**Comment by torrin47** [comment]
Fantastico!
