### ISSUE TITLE
Re-enable matching accounts for new requests if found and treat like existing account after re-enable-ment.

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#78]
Chatted with Solana today and deciding whether we should delete or disable accounts of folks from the response.

Deleting seems cleaner, but Solana was leaning toward disabling since a lot of these people do cycle back in eventually.

But my thought is... if we disable folks that really only ever work on responses, most likely than not, they'll have no idea how to get in to their account a year from now and will just end up getting a new account created regardless - or creating a headache. 

Can we somehow also use to tool to identify if a disabled account is associated with a given email (maybe we already are and there's no distinction in the current list, not sure)? But if so, provide the option to reenable in the tool?

Thoughts?

**Comment by tbock** [comment]
idk... still seems like just point to AGOL like discussed in issue #51 is best.  What's the benefit of "disabling" assuming thats something we can actually do?  They retain some content/group permissions? What about their content?

**Comment by jlherring** [comment]
Exactly, you could pull them back in if needed, and think their content is untouched if you just disable. Think it is def related to #51 - but on the other side. In my mind, #51 deals with decommissioning/ending a response.

Here I'm thinking more about when a new response starts - we'd need to be able to access and kickstart the disabled accounts from a previous response in a new context.

**Comment by tbock** [comment]
So really just finding a matching disabled account like we find existing accounts and reenabling it and then treating it like an existing account.  Disabling/Deleting should still be handled like discussed in #51?

**Comment by jlherring** [comment]
That's my thinking

**Comment by tbock** [comment]
to do list 
- [ ] re-enable disable accounts
- [ ] notify users their account has been re-enabled
- [ ] ??? figure out what to do about password ???
