### ISSUE TITLE
Send new project request emails to Coordinator Admin group members

### ISSUE THREAD

**Issue by jlherring** [USEPA/GeoPlatform-Request-Tool#81]
Notices about new projects are hardwired to Cheryl/Jenny/Rob and still going to Rob's Innovate email that no longer exists. Need to swap to Rob's EPA email

**Comment by tbock** [comment]
Let make this NOT hardcoded.  @tommckennon please add a attribute to users (we already have a model for this) to indicate who should be notified for new project quests and just use their user's email address.

**Comment by tommckennon** [comment]
To confirm, is this for Request Tool email notifications that include subject text _Project Request for Review in GeoPlatform Account Request Tool_. If so, I notice presently that the recipient emails for those notifications are configurable (RECIPIENT_EMAILS). If we don't want to manually configure these email recipients, I'm wondering shall the email recipients for the project requests be apart of a user group, such as the Sponsors group? There's a few user groups, so wondering if it suits those members to receive these emails, or perhaps anew user group strictly for this purpose?

**Comment by tbock** [comment]
No.  It can't be sponsors ... that's too broad.  Though you could just create another group and we could use that.

**Comment by tommckennon** [comment]
@jlherring , go forth on a new group for these new project email recipients? If so, good name for group?

**Comment by tbock** [comment]
@tommckennon We already have a group called Coordinator Admins.  You can use that.

**Comment by jlherring** [comment]
The group we use is now "Sponsors and Delegates (required to edit/approve)" - do we need to swap to this @tbock? or already done?

**Comment by tbock** [comment]
No thats a different group. Coordinator Admins need to be assigned so they get this email.
